### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by devnix** [kevinmartin/direct.js#1]
Hey! I've found this package and I think I will be using it in my future simple projects to keep modularity. Do you think you could do a Bower package?

Thank you for this library! :smiley:

**Comment by kevinmartin** [comment]
@DevNIX this package hasn't been updated in about 4 years. Though it works perfectly and stuff, I'm not really maintaining it anymore. If you wish, you could go ahead, fork it, and release it on bower yourself. :)

On the other hand, you could just `npm install --save direct` and link to `node_modules/direct/direct.js` in your build scripts (assuming you compile your scripts together).
